package homework_testing.fifth;

public class Circle extends Shape{
    protected double radius;
    Circle() {}
    Circle(double radius) {
        this.radius = radius;
    }
    Circle(double radius, String color, boolean filled) {
        this.radius = radius;
        this.color = color;
        this.filled = filled;
    }
    public double getRadius() {
        return radius;
    }
    public void setRadius(double radius) {
        this.radius = radius;
    }
    public double getArea() {
        return radius * radius * Math.PI;
    }
    public double getPerimeter() {
        return radius * 2 * Math.PI;
    }
    public String toString() {
        return "This is a circle has radius of " + getRadius()
                + " and color is " + getColor() + " and filled " + isFilled()
                + " and area is " + getArea() + " and perimeter is " + getPerimeter();
    }

    public static void main(String[] args) {
        System.out.println("Test Circle******************");
        Circle c1 = new Circle(1.1);
        System.out.println("Show Circle");
        System.out.println(c1.toString());
        System.out.println("Change radius");
        c1.setRadius(1.0);
        System.out.println("Now the radius is " + c1.getRadius());
        System.out.println("Now the Area is " + c1.getArea());
        System.out.println("Now the Perimeter is " + c1.getPerimeter());
        System.out.println("Change color");
        c1.setColor("red");
        System.out.println("Now the color is " + c1.getColor());
        System.out.println("Change filled");
        c1.setFilled(true);
        System.out.println("Now the filled is " + c1.isFilled());
        Circle c2 = new Circle(1.2, "blue", true);
        Circle c3 = new Circle();
        System.out.println("Show other circles generated by other methods");
        System.out.println(c2.toString());
        System.out.println(c3.toString());
    }
}
